name: PHP_CodeSniffer
on: push
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "latest"
          coverage: none
          tools: composer:v2, cs2pr
      - name: Install Composer dependencies for PHP
        uses: "ramsey/composer-install@v2"
      - name: Detect coding standard violations
        run: composer lint

